version: '3.8'

services:
  # Loki - Log Aggregation System
  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "3998:3100"
    volumes:
      - ./configs/loki-config.yml:/etc/loki/local-config.yaml
      - ./data/loki:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - grafana-stack
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Promtail - Log Collector
  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./configs/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - grafana-stack
    restart: unless-stopped
    depends_on:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Grafana - Visualization & Dashboard
  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    ports:
      - "3999:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
      - ./configs/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./configs/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./dashboards:/etc/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_LOG_LEVEL=info
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    networks:
      - grafana-stack
    restart: unless-stopped
    depends_on:
      - loki
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  grafana-stack:
    driver: bridge
    name: grafana-stack

volumes:
  loki-data:
    driver: local
  grafana-data:
    driver: local
