services:
  # Loki - Log Aggregation System
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "${LOKI_PORT:-3998}:3100"
    volumes:
      - loki-data:/loki
    networks:
      - default
    restart: unless-stopped

  # Promtail - Log Collector (Minimal)
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      # - ./configs/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # command: -config.file=/etc/promtail/config.yml
    networks:
      - default
    restart: unless-stopped
    depends_on:
      - loki

  # Grafana - Visualization & Dashboard
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "${GRAFANA_PORT:-3999}:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin123}
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - default
    restart: unless-stopped
    depends_on:
      - loki

  # ---------- Sentry Dependencies ----------
  redis:
    image: redis:alpine
    container_name: sentry_redis
    restart: unless-stopped
    volumes:
      - sentry_redis:/data
    networks:
      - default

  postgres:
    image: postgres:14
    container_name: sentry_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sentry
      POSTGRES_PASSWORD: sentry
      POSTGRES_DB: sentry
    volumes:
      - sentry_postgres:/var/lib/postgresql/data
    networks:
      - default

  # ---------- Sentry Core ----------
  sentry:
    image: sentry:latest
    container_name: sentry_web
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    environment:
      SENTRY_SECRET_KEY: "${SENTRY_SECRET_KEY:-ac1cd0f73997c89d45917853f4a7fed43c0d7c4f2b795ec89225dc8eb7c1b5b6}"
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_DB_NAME: sentry
      SENTRY_REDIS_HOST: redis
      SENTRY_REDIS_PORT: 6379
    ports:
      - "${SENTRY_PORT:-3997}:9000"
    volumes:
      - sentry_data:/var/lib/sentry/files
    networks:
      - default

  cron:
    image: sentry:latest
    container_name: sentry_cron
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    command: run cron
    environment:
      SENTRY_SECRET_KEY: "${SENTRY_SECRET_KEY:-ac1cd0f73997c89d45917853f4a7fed43c0d7c4f2b795ec89225dc8eb7c1b5b6}"
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_DB_NAME: sentry
      SENTRY_REDIS_HOST: redis
      SENTRY_REDIS_PORT: 6379
    volumes:
      - sentry_data:/var/lib/sentry/files
    networks:
      - default

  worker:
    image: getsentry/sentry:latest
    container_name: sentry_worker
    restart: unless-stopped
    depends_on:
      - redis
      - postgres
    command: run worker
    environment:
      SENTRY_SECRET_KEY: "${SENTRY_SECRET_KEY:-ac1cd0f73997c89d45917853f4a7fed43c0d7c4f2b795ec89225dc8eb7c1b5b6}"
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_DB_USER: sentry
      SENTRY_DB_PASSWORD: sentry
      SENTRY_DB_NAME: sentry
      SENTRY_REDIS_HOST: redis
      SENTRY_REDIS_PORT: 6379
    volumes:
      - sentry_data:/var/lib/sentry/files
    networks:
      - default


# ---------- Networks & Volumes ----------
networks:
  default:
    driver: bridge
    name: ${NETWORK_NAME:-grafana-stack}

volumes:
  loki-data:
  grafana-data:
  sentry_postgres:
  sentry_redis:
  sentry_data:
