server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # System logs
  - job_name: system-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: system-logs
          host: docker-host
          __path__: /var/log/*log

  # Docker container logs
  - job_name: docker-logs
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
        filters:
          - name: label
            values: ["logging=promtail"]
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'logstream'
      - source_labels: ['__meta_docker_container_label_logging_jobname']
        target_label: 'job'

  # Nginx logs (if available)
  - job_name: nginx-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: nginx-logs
          host: docker-host
          __path__: /var/log/nginx/*log

  # Apache logs (if available)
  - job_name: apache-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: apache-logs
          host: docker-host
          __path__: /var/log/apache2/*log

  # Journal logs (systemd)
  - job_name: journal-logs
    journal:
      max_age: 12h
      labels:
        job: systemd-journal
        host: docker-host

  # Additional container logs using file_sd
  - job_name: containers-file-discovery
    file_sd_configs:
      - files:
        - /etc/promtail/targets.json
        refresh_interval: 10s

pipeline_stages:
  - json:
      expressions:
        output: log
        stream: stream
        attrs:
  - json:
      expressions:
        tag: attrs.tag
      source: attrs
  - regex:
      expression: (?P<container_name>(?:[^|]*))\|?
      source: tag
  - timestamp:
      format: RFC3339Nano
      source: time
  - labels:
      stream:
      container_name:
  - output:
      source: output
